{% set name = "pystack" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystack-{{ version }}.tar.gz
  sha256: 6b7362d4a2688270511a1f0868fddcc02f0db20950ecdb2c990bff777e5737a5

build:
  skip: true  # [not linux]
  entry_points:
    - pystack=pystack.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - elfutils
    - python
    - setuptools
    - wheel
    - cython
    - pip
  run:
    - python

test:
  imports:
    - pystack
  commands:
    - pip check
    - pystack --help
  requires:
    - pip

about:
  home: https://github.com/bloomberg/pystack
  summary: Analysis of the stack of remote python processes
  description: |
    PyStack is a tool that uses forbidden magic to let you
    inspect the stack frames of a running Python process or
    a Python core dump.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://bloomberg.github.io/pystack/
  dev_url: https://github.com/bloomberg/pystack

extra:
  recipe-maintainers:
    - beenje
