schema_version: 1

context:
  name: pystack
  version: "1.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pystack-${{ version }}.tar.gz
  sha256: 1469ffcabcad89ef7e591ee6f4e11610e9e36caa5efb4fb0db599b92e5dbb072

build:
  number: 0
  skip: not linux
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pystack=pystack.__main__:main

requirements:
  ignore_run_exports:
    by_name:
      # Both packages are required for cmake to find elfutils libraries
      # but are reported are overdepending
      - libzlib
      - liblzma
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - elfutils
    - zlib
    - liblzma-devel
    - python
    - scikit-build-core >=0.9
    - nanobind >=1.8
    - pip
  run:
    - python

tests:
  - python:
      pip_check: true
      imports:
        - pystack
  - script:
      - pystack --help

about:
  summary: Analysis of the stack of remote python processes
  description: |
    PyStack is a tool that uses forbidden magic to let you
    inspect the stack frames of a running Python process or
    a Python core dump.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/bloomberg/pystack
  repository: https://github.com/bloomberg/pystack
  documentation: https://bloomberg.github.io/pystack/

extra:
  recipe-maintainers:
    - beenje
